project_id = "ltjnbmvfjjphljcavrmp"

[functions.process-analysis]
verify_jwt = false

[functions.handle-webhook]
verify_jwt = false

[functions.generate-metrics]
verify_jwt = false

[functions.monitor-conversations]
verify_jwt = false

[functions.process-orphan-messages]
verify_jwt = false

[functions.admin-reset-users]
verify_jwt = true

[functions.admin-reset-data]
verify_jwt = true

[functions.admin-promote-user]
verify_jwt = true

[functions.analyze-sales-conversation]
verify_jwt = false

[functions.admin-delete-user]
verify_jwt = true

[functions.admin-toggle-role]
verify_jwt = true

[functions.force-unlock-and-monitor]
verify_jwt = false
