project_id = "ltjnbmvfjjphljcavrmp"

[functions.process-analysis]
verify_jwt = false

[functions.handle-webhook]
verify_jwt = false

[functions.generate-metrics]
verify_jwt = false

[functions.monitor-conversations]
verify_jwt = false

[functions.admin-reset-users]
verify_jwt = false

[functions.admin-promote-user]
verify_jwt = false